// 태양계 친구들 데이터
const PLANETS = [
  {
    id: 'sun',
    name: '태양',
    nickname: '뜨거운 친구',
    emoji: '☀️',
    color: '#FFA500',
    glow: '#FFD93D',
    size: 1.6,
    orbitRadius: 0,
    orbitSpeed: 0,
    spinSpeed: 60,
    intro: '내가 없으면 다른 친구들은 깜깜해요!',
    audioText: '안녕! 나는 태양이야. 내가 없으면 다른 친구들은 모두 깜깜해. 나는 엄청 뜨겁고, 모두를 빙글빙글 돌게 해줘.',
    facts: [
      { icon: '📏', label: '크기', text: '지구보다 100만 배나 더 커요!' },
      { icon: '🔥', label: '온도', text: '엄청엄청 뜨거워서 가까이 가면 안 돼요' },
      { icon: '⭐', label: '역할', text: '모두를 빙글빙글 돌게 해요' },
    ],
  },
  {
    id: 'mercury',
    name: '수성',
    nickname: '꼬마 수성이',
    emoji: '☿',
    color: '#A0826D',
    glow: '#C9A07B',
    size: 0.5,
    orbitRadius: 2.0,
    orbitSpeed: 24,
    spinSpeed: 80,
    intro: '나는 태양이랑 제일 친한 꼬마야!',
    audioText: '안녕! 나는 수성이야. 태양이랑 제일 가까운 꼬마 행성이지. 낮엔 너무 덥고, 밤엔 너무 추워. 하루가 59일이나 걸려.',
    facts: [
      { icon: '🤏', label: '크기', text: '8개 행성 중에 제일 작아요' },
      { icon: '🌗', label: '낮과 밤', text: '낮엔 너~무 덥고, 밤엔 너~무 추워요', interactive: 'daynight' },
      { icon: '🕐', label: '하루', text: '하루(자전)가 59일이나 걸려요' },
    ],
  },
  {
    id: 'venus',
    name: '금성',
    nickname: '반짝이 금성이',
    emoji: '♀',
    color: '#E8B87A',
    glow: '#F5D7A0',
    size: 0.85,
    orbitRadius: 2.7,
    orbitSpeed: 32,
    spinSpeed: 100,
    intro: '밤하늘에서 제일 반짝거리는 별이 나야!',
    audioText: '안녕! 나는 금성이야. 밤하늘에서 제일 반짝거리는 별이 바로 나야. 지구랑 크기가 똑같아서 쌍둥이 같지.',
    facts: [
      { icon: '👯', label: '크기', text: '지구랑 거의 똑같아서 쌍둥이 같아요' },
      { icon: '☁️', label: '구름', text: '구름이 가득해서 얼굴이 잘 안 보여요' },
      { icon: '🥵', label: '온도', text: '태양계에서 제일 뜨거운 행성이에요' },
    ],
  },
  {
    id: 'earth',
    name: '지구',
    nickname: '우리 집 지구',
    emoji: '🌍',
    color: '#4A90E2',
    glow: '#7FB8F0',
    size: 0.9,
    orbitRadius: 3.4,
    orbitSpeed: 40,
    spinSpeed: 12,
    intro: '우리가 사는 곳! 파랗고 예쁜 우리 집이에요',
    audioText: '안녕! 나는 지구야. 우리 모두가 사는 곳이지. 물이 많아서 파랗게 보여. 나무, 동물, 사람이 함께 살아.',
    facts: [
      { icon: '💧', label: '물', text: '물이 많아서 파랗게 보여요' },
      { icon: '🌳', label: '생명', text: '나무, 동물, 사람이 살아요' },
      { icon: '🌙', label: '친구', text: '달이 우리를 따라다녀요' },
    ],
  },
  {
    id: 'mars',
    name: '화성',
    nickname: '빨간 화성이',
    emoji: '♂',
    color: '#CD5C3A',
    glow: '#E07A55',
    size: 0.7,
    orbitRadius: 4.2,
    orbitSpeed: 50,
    spinSpeed: 14,
    intro: '나는 빨간 모래로 뒤덮인 사막 행성이야!',
    audioText: '안녕! 나는 화성이야. 빨간 모래로 뒤덮인 사막 행성이지. 에베레스트보다 세 배나 높은 산이 있어. 로봇 친구들이 놀러 오기도 해.',
    facts: [
      { icon: '🟥', label: '색깔', text: '흙이 빨개서 빨간 행성이라고 불려요' },
      { icon: '🏔️', label: '큰 산', text: '에베레스트보다 3배 더 높은 산이 있어요' },
      { icon: '🤖', label: '손님', text: '지구에서 로봇 친구들이 놀러 와요' },
    ],
  },
  {
    id: 'jupiter',
    name: '목성',
    nickname: '거인 목성이',
    emoji: '♃',
    color: '#D4A373',
    glow: '#E8C39B',
    size: 1.4,
    orbitRadius: 5.2,
    orbitSpeed: 70,
    spinSpeed: 8,
    intro: '나는 태양계에서 제일 큰 거인이야!',
    audioText: '안녕! 나는 목성이야. 태양계에서 제일 큰 거인이지. 지구 1300개를 한꺼번에 넣을 수도 있어. 빨간 점은 엄청 큰 태풍이야.',
    moons: [{ name: '이오', color: '#F5D547' }],
    facts: [
      { icon: '🐘', label: '크기', text: '지구 1,300개를 넣을 수 있어요' },
      { icon: '🌪️', label: '빨간 점', text: '빨간 점은 엄청 큰 태풍이에요' },
      { icon: '🟡', label: '친구', text: '위성이 95명! 그중 이오는 노란색이에요' },
    ],
  },
  {
    id: 'saturn',
    name: '토성',
    nickname: '모자 쓴 토성이',
    emoji: '♄',
    color: '#E5C687',
    glow: '#F2D9A8',
    size: 1.25,
    orbitRadius: 6.1,
    orbitSpeed: 90,
    spinSpeed: 9,
    intro: '내 멋진 모자를 봐줘!',
    audioText: '안녕! 나는 토성이야. 내 멋진 고리 모자를 봐줘. 사실 고리는 얼음이랑 돌멩이로 만들어졌어. 큰 욕조에 넣으면 둥둥 뜰 수 있을 만큼 가벼워.',
    hasRings: true,
    facts: [
      { icon: '💍', label: '고리', text: '고리는 얼음이랑 돌멩이로 만들어졌어요', interactive: 'rings' },
      { icon: '🛁', label: '무게', text: '물보다 가벼워서 욕조에 띄울 수도 있어요' },
      { icon: '👨\u200d👩\u200d👧\u200d👦', label: '친구', text: '위성이 140명도 넘어요' },
    ],
  },
  {
    id: 'uranus',
    name: '천왕성',
    nickname: '누워있는 천왕성이',
    emoji: '♅',
    color: '#7FDBDA',
    glow: '#A5E8E7',
    size: 1.05,
    orbitRadius: 6.9,
    orbitSpeed: 110,
    spinSpeed: 11,
    tiltAxis: true,
    intro: '나는 옆으로 누워서 굴러다녀요!',
    audioText: '안녕! 나는 천왕성이야. 다른 행성들과 다르게 옆으로 누워서 굴러다녀. 파란 가스로 이루어져 있고, 영하 220도로 엄청 차가워.',
    facts: [
      { icon: '🛌', label: '회전축', text: '다른 행성과 다르게 옆으로 누워서 돌아요', interactive: 'tilt' },
      { icon: '💨', label: '재료', text: '파란색 가스로 이루어져 있어요' },
      { icon: '🥶', label: '온도', text: '엄청엄청 차가워요. 영하 220도!' },
    ],
  },
  {
    id: 'neptune',
    name: '해왕성',
    nickname: '바람쟁이 해왕성이',
    emoji: '♆',
    color: '#4166F5',
    glow: '#6E8AFA',
    size: 1.0,
    orbitRadius: 7.7,
    orbitSpeed: 130,
    spinSpeed: 10,
    intro: '나는 가장 멀리 있는 파란 친구야!',
    audioText: '안녕! 나는 해왕성이야. 태양에서 가장 멀리 있는 파란 친구지. 바람이 시속 2000킬로미터로 불어. 트리톤이라는 위성은 거꾸로 돌아.',
    moons: [{ name: '트리톤', color: '#D8E0F0' }],
    facts: [
      { icon: '🌬️', label: '바람', text: '바람이 시속 2,000km로 불어요' },
      { icon: '📅', label: '1년', text: '태양에서 너무 멀어서 1년이 165년이에요' },
      { icon: '🔄', label: '친구', text: '트리톤 위성은 거꾸로 돌아요' },
    ],
  },
];

window.PLANETS = PLANETS;
